// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9DRVreLqCyHSecyifmovL7
// Component: TJyhvy_W3Z38Fk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 5q0d-nd0cELSvd/component
import TextInput from "../../TextInput"; // plasmic-import: M4Ie8C1t_mn5s/component
import Checkbox from "../../Checkbox"; // plasmic-import: 5RV4oyktt5eAJK/component
import Footer from "../../Footer"; // plasmic-import: 6zsXKEMs4WOlZZ/component
import { useScreenVariants as useScreenVariantsruCWDbKoSkemq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ruC-wDbKoSKEMQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: 9DRVreLqCyHSecyifmovL7/projectcss
import sty from "./PlasmicSignUp.module.css"; // plasmic-import: TJyhvy_W3Z38Fk/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: -GJovX1u1DwmuB/icon
import tiffanyTertipesNxcs8Wwj9J0UnsplashjpgV4YrTzTnSdVfnX from "./images/tiffanyTertipesNxcs8Wwj9J0Unsplashjpg.jpeg"; // plasmic-import: V4yrTZTnSDVfnX/picture
import stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgQ1TTCkqGzbCvha from "./images/stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpg.jpeg"; // plasmic-import: q1tTCkqGzbCvha/picture
import greenChameleonS9Cc2SKySjmUnsplashjpgFlcnKSgeQywJyu from "./images/greenChameleonS9Cc2SKySjmUnsplashjpg.jpeg"; // plasmic-import: flcnKSgeQywJyu/picture

export const PlasmicSignUp__VariantProps = new Array();

export const PlasmicSignUp__ArgProps = new Array();

function PlasmicSignUp__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsruCWDbKoSkemq()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"mainSection"}
            data-plasmic-override={overrides.mainSection}
            className={classNames(projectcss.all, sty.mainSection)}
          >
            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__z2O3Z)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__haYq)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__lXvyy)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__uxmbt)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Sign Up"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i1KmZ
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                        }
                      </div>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__sGCrf)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qo2Tj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "lazy"
                          : "lazy"
                      }
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgQ1TTCkqGzbCvha,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                          : {
                              src: tiffanyTertipesNxcs8Wwj9J0UnsplashjpgV4YrTzTnSdVfnX,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                      }
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"mainSection2"}
              data-plasmic-override={overrides.mainSection2}
              className={classNames(projectcss.all, sty.mainSection2)}
            >
              <div className={classNames(projectcss.all, sty.columns__ncsYg)}>
                <div className={classNames(projectcss.all, sty.column___3HjEd)}>
                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {"Register"}
                    </h2>

                    <label
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label__cz7V4
                      )}
                    >
                      {"Name"}
                    </label>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__o2Mj4
                      )}
                      placeholder={" "}
                    />

                    <label
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label___3F72V
                      )}
                    >
                      {"Email"}
                    </label>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput___8Lw4I
                      )}
                      placeholder={" "}
                    />

                    <label
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label__n9D84
                      )}
                    >
                      {"Phone"}
                    </label>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__ae378
                      )}
                      placeholder={" "}
                    />

                    <Checkbox
                      data-plasmic-name={"checkbox"}
                      data-plasmic-override={overrides.checkbox}
                      className={classNames("__wab_instance", sty.checkbox)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p6He6
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "I understand that this form is \nstoring my submitted information \nso I can be contacted."
                          : "I understand that this form is storing"}
                      </div>
                    </Checkbox>

                    <p.Stack
                      as={"a"}
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link
                      )}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__lyPzk)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__u15Us
                        )}
                      >
                        {"Send Now"}
                      </div>

                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xXq6P)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__ymzxX)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kq7Of)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: greenChameleonS9Cc2SKySjmUnsplashjpgFlcnKSgeQywJyu,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "mainSection",
    "pageBanner",
    "h1",
    "mainSection2",
    "container4",
    "h2",
    "checkbox",
    "link",
    "footer"
  ],

  header: ["header"],
  mainSection: [
    "mainSection",
    "pageBanner",
    "h1",
    "mainSection2",
    "container4",
    "h2",
    "checkbox",
    "link"
  ],

  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  mainSection2: ["mainSection2", "container4", "h2", "checkbox", "link"],
  container4: ["container4", "h2", "checkbox", "link"],
  h2: ["h2"],
  checkbox: ["checkbox"],
  link: ["link"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSignUp__ArgProps,
      internalVariantPropNames: PlasmicSignUp__VariantProps
    });

    return PlasmicSignUp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUp";
  } else {
    func.displayName = `PlasmicSignUp.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUp = Object.assign(
  // Top-level PlasmicSignUp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    mainSection: makeNodeComponent("mainSection"),
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    mainSection2: makeNodeComponent("mainSection2"),
    container4: makeNodeComponent("container4"),
    h2: makeNodeComponent("h2"),
    checkbox: makeNodeComponent("checkbox"),
    link: makeNodeComponent("link"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicSignUp
    internalVariantProps: PlasmicSignUp__VariantProps,
    internalArgProps: PlasmicSignUp__ArgProps
  }
);

export default PlasmicSignUp;
/* prettier-ignore-end */
