// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9DRVreLqCyHSecyifmovL7
// Component: 6e3of_VAaHX-mW
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 5q0d-nd0cELSvd/component
import Button from "../../Button"; // plasmic-import: QELWMjce80Acl/component
import Footer from "../../Footer"; // plasmic-import: 6zsXKEMs4WOlZZ/component
import { useScreenVariants as useScreenVariantsruCWDbKoSkemq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ruC-wDbKoSKEMQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: 9DRVreLqCyHSecyifmovL7/projectcss
import sty from "./PlasmicBlog.module.css"; // plasmic-import: 6e3of_VAaHX-mW/css
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: gm_BEJaLC5ip7u/icon
import neonbrand3GznpblImWcUnsplashjpgOJyT9CsCm1Hp01 from "./images/neonbrand3GznpblImWcUnsplashjpg.jpeg"; // plasmic-import: OJyT9csCM1Hp01/picture
import istockphoto1306171737170667Ajpg27Ayi3VVoenRfIi from "./images/istockphoto1306171737170667Ajpg2.jpeg"; // plasmic-import: 7Ayi3vVoenRFIi/picture
import fakurianDesignPPTwRTkvXqUnsplashjpgRm7ZzXdXpQ73KM from "./images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg"; // plasmic-import: Rm7ZzXDXpQ73kM/picture
import fakurianDesignLfbhDph3QYUnsplashjpgD6SiPplrenPk6K from "./images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg"; // plasmic-import: D6siPPLRENPk6K/picture
import xpsOcAuPlfZxEcUnsplashjpgHlAqfQQhYGiTVm from "./images/xpsOcAuPlfZxEcUnsplashjpg.jpeg"; // plasmic-import: hlAqfQQhYGiTVm/picture
import corinneKutzTMi2R5NfoUnsplashjpgGzBj5Y3ZkRfGbA from "./images/corinneKutzTMi2R5NfoUnsplashjpg.jpeg"; // plasmic-import: gzBJ5y3ZkRFGbA/picture
import stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgQ1TTCkqGzbCvha from "./images/stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpg.jpeg"; // plasmic-import: q1tTCkqGzbCvha/picture

export const PlasmicBlog__VariantProps = new Array();

export const PlasmicBlog__ArgProps = new Array();

function PlasmicBlog__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsruCWDbKoSkemq()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__yzDzT)}>
            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__tfZqk)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__tqCby)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__kcQzi)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ifs3J)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Blog"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lg13A
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                        }
                      </div>
                    </p.Stack>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__fccO)}>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__jkin7)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "lazy"
                          : "lazy"
                      }
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: neonbrand3GznpblImWcUnsplashjpgOJyT9CsCm1Hp01,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                          : {
                              src: neonbrand3GznpblImWcUnsplashjpgOJyT9CsCm1Hp01,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                      }
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__bpNGi)}>
              <div className={classNames(projectcss.all, sty.freeBox__f61I)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__v1UQm)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__xpwJo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__odNMf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rqnm7
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__kDCq)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: istockphoto1306171737170667Ajpg27Ayi3VVoenRfIi,
                            fullWidth: 509,
                            fullHeight: 340,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__yiuZw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aMtOn
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__p61EA
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hBwOv
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___7KNi8
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jldp0
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Read post"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__vEj5S)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__uWt3Q)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__idtAh
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__nrj58)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: fakurianDesignPPTwRTkvXqUnsplashjpgRm7ZzXdXpQ73KM,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rYwra
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aihqm
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4___4RtZ
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0IPpq
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__o7TgZ
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__plPkF
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__lOqf)}>
                    <div
                      className={classNames(projectcss.all, sty.columns__li9Qg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__jLyb1
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xcDyo)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: fakurianDesignLfbhDph3QYUnsplashjpgD6SiPplrenPk6K,
                            fullWidth: 1920,
                            fullHeight: 1080,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__bAvAe
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nOlcr
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__kxhxB
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yCgD
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__mEsic
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__cq5Hw
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__aknu3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__bDEdY)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nL1Mo
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__uUfWl)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: xpsOcAuPlfZxEcUnsplashjpgHlAqfQQhYGiTVm,
                            fullWidth: 640,
                            fullHeight: 360,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6RvW
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gsuoh
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__bPpqm
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ccJFg
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___7EhqF
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__buTAw
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___5GlpN)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__f3Nwv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cgjg0
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yU3D)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: corinneKutzTMi2R5NfoUnsplashjpgGzBj5Y3ZkRfGbA,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6Mf4H
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oqq47
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__zMyx0
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vb4Po
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__fb2PG
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__t4Ajf
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__cjG6G)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__mWpsL)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__r4UQl
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___3PTm)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpgQ1TTCkqGzbCvha,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cdIOv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pdXzn
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__vqNc4
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___26LP
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___6L3NY
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___9M7XM
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__xvIhb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__eU6Sr)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dqBxU
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__n9Jd)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: neonbrand3GznpblImWcUnsplashjpgOJyT9CsCm1Hp01,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ereoi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8B1Ha
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__zjOtM
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7YzH0
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__ug52K
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__v0CDj
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__sAjW)}>
                    <div
                      className={classNames(projectcss.all, sty.columns__xi8Yv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3RwuX
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___6Lpkk)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: neonbrand3GznpblImWcUnsplashjpgOJyT9CsCm1Hp01,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__vGasM
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__awIk
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__fKYac
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__saYiR
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__bcvG
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__tFcLy
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                          >
                            {"Learn more"}
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanner", "h1", "footer"],
  header: ["header"],
  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlog__ArgProps,
      internalVariantPropNames: PlasmicBlog__VariantProps
    });

    return PlasmicBlog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog";
  } else {
    func.displayName = `PlasmicBlog.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog = Object.assign(
  // Top-level PlasmicBlog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicBlog
    internalVariantProps: PlasmicBlog__VariantProps,
    internalArgProps: PlasmicBlog__ArgProps
  }
);

export default PlasmicBlog;
/* prettier-ignore-end */
