// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9DRVreLqCyHSecyifmovL7
// Component: KOg7It0rElZcK
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: QELWMjce80Acl/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: 9DRVreLqCyHSecyifmovL7/projectcss
import sty from "./PlasmicBlogPosts.module.css"; // plasmic-import: KOg7It0rElZcK/css
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: gm_BEJaLC5ip7u/icon
import fakurianDesignPPTwRTkvXqUnsplashjpgRm7ZzXdXpQ73KM from "./images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg"; // plasmic-import: Rm7ZzXDXpQ73kM/picture
import fakurianDesignLfbhDph3QYUnsplashjpgD6SiPplrenPk6K from "./images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg"; // plasmic-import: D6siPPLRENPk6K/picture
import blog2390X290JpgLzpZ9NRqu1Lufl from "./images/blog2390X290Jpg.jpeg"; // plasmic-import: lzpZ9NRqu1lufl/picture

export const PlasmicBlogPosts__VariantProps = new Array();

export const PlasmicBlogPosts__ArgProps = new Array();

function PlasmicBlogPosts__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__tEbUw)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {"Blog"}
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__w9R0Q
          )}
        >
          {
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
          }
        </div>

        <div className={classNames(projectcss.all, sty.columns__b1NYx)}>
          <div className={classNames(projectcss.all, sty.column__dgCf)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__gJpZ)}
              displayHeight={"230px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: fakurianDesignPPTwRTkvXqUnsplashjpgRm7ZzXdXpQ73KM,
                fullWidth: 1920,
                fullHeight: 1280,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__hma3X)}>
              <div className={classNames(projectcss.all, sty.column__v5XpK)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ex9Ci
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__nWbXs
                  )}
                >
                  {"Convincing reasons you need to learn"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__txdy
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__s6RE6)}
                  color={"softBlue"}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__irPak)}
                      role={"img"}
                    />
                  }
                  shape={"rounded"}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iYrLb
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__kqsvm)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__clSlJ)}
              displayHeight={"230px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: fakurianDesignLfbhDph3QYUnsplashjpgD6SiPplrenPk6K,
                fullWidth: 1920,
                fullHeight: 1080,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__xLid3)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yLq8Y)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aSjAn
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__umcFj
                  )}
                >
                  {"The five devices you need to work anytime"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ih8L
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__ximyp)}
                  color={"softBlue"}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__xwkVh)}
                      role={"img"}
                    />
                  }
                  shape={"rounded"}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lT0WO
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__rbbSi)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__cEsT)}
              displayHeight={"230px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: blog2390X290JpgLzpZ9NRqu1Lufl,
                fullWidth: 390,
                fullHeight: 290,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__plZmt)}>
              <div className={classNames(projectcss.all, sty.column__zeQi1)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wI7Xp
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__poBlH
                  )}
                >
                  {"Tiktok Illegally collecting data sharing"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eg8Oj
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__dMfR)}
                  color={"softBlue"}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__rPiR6)}
                      role={"img"}
                    />
                  }
                  shape={"rounded"}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qtXiW
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlogPosts__ArgProps,
      internalVariantPropNames: PlasmicBlogPosts__VariantProps
    });

    return PlasmicBlogPosts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogPosts";
  } else {
    func.displayName = `PlasmicBlogPosts.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogPosts = Object.assign(
  // Top-level PlasmicBlogPosts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),
    // Metadata about props expected for PlasmicBlogPosts
    internalVariantProps: PlasmicBlogPosts__VariantProps,
    internalArgProps: PlasmicBlogPosts__ArgProps
  }
);

export default PlasmicBlogPosts;
/* prettier-ignore-end */
